### ISSUE TITLE
why not use inputted original password text compare with the setting basic password text?

### ISSUE THREAD

**Issue by gouhan** [yuzd/Hangfire.Dashboard.BasicAuthorization#1]
in BasicAuthAuthorizationUser.cs, when validate user inputted password compare with the setted password.
`using (var cryptoProvider = SHA1.Create())
                {
                    Password = cryptoProvider.ComputeHash(Encoding.UTF8.GetBytes(value));
                }`
and compared
`using (var cryptoProvider = SHA1.Create())
                {
                    byte[] passwordHash = cryptoProvider.ComputeHash(Encoding.UTF8.GetBytes(password));
                    return StructuralComparisons.StructuralEqualityComparer.Equals(passwordHash, Password);
                }`
.
the same to use original password text compare with

**Comment by yuzd** [comment]
if want to protected password , you can use set Password value by bytes[].
