### ISSUE TITLE
I'm not able to see my dashboard in the production environment

### ISSUE THREAD

**Issue by flabioassuncao** [yuzd/Hangfire.Dashboard.BasicAuthorization#3]
In the local environment work fine, but when I try to see on Azure I receive the 401 error, the credentials dialog doesn't show up and I can't put username and password.

can you help me? Thanks

![image](https://user-images.githubusercontent.com/11317582/100350543-f3d67f80-2fe1-11eb-92d5-ef7b626d124f.png)

**Comment by yuzd** [comment]
Demo:
https://github.com/yuzd/Hangfire.HttpJob/blob/master/Test/TestHangfire/HangfireCollectionExtensions.cs

**Comment by night-king** [comment]
Me to,
It can work in debug or development env. but  I receive the 401 error, the credentials dialog doesn't show up in PRODUCTION env.

**Comment by SamuelFormigheri** [comment]
@night-king I faced the same issue. In my case the error was occurring in production cause the library uses the header "WWW-Authenticate" and I think our production environment was blocking that. To resolve the issue I didn't use this library and implement an authentication using Jwt.

**Comment by srad** [comment]
Same issue as @night-king. Blank page in production. Would be rather strange if it's true what @SamuelFormigheri said.
Is anyone maintainnig this package?

**Comment by SamuelFormigheri** [comment]
> Same issue as @night-king. Blank page in production. Would be rather strange if it's true what @SamuelFormigheri said. Is anyone maintainnig this package?

I don't think it's currently active maintained. But the way I create a custom auth middleware was that. Hope it helps.

```
Program.cs:

app.UseHangfireDashboard("/hangfire", new DashboardOptions
{
    AppPath = "#",
    IgnoreAntiforgeryToken = true,
    DashboardTitle = "Title",
    Authorization = new[] {
        new AuthMiddleware()
    }
});

AuthMiddlewareClass:

public class AuthMiddleware : IDashboardAuthorizationFilter
    {
        public AuthMiddleware() { }

        private bool ValidateToken(string token)
        {
            if (!JWT.IsValidToken(token)) // These was a custom implementation to validate my jwt
                return false;

            return true;
        }

        public bool Authorize(DashboardContext ctx)
        {

            HttpContext context = ctx.GetHttpContext();

            string? token = context.Request.Cookies["Token"];

            if (string.IsNullOrEmpty(token))
                return false;

            return ValidateToken(token);
        }
    }
